version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  backend:
    image: labamoon/final_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: labamoon/final_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - docs:/usr/share/nginx/html/api/docs/
      - /etc/letsencrypt/live/food-solutions.zapto.org/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/food-solutions.zapto.org/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - backend
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
  docs: