# recipes constants

USER_MAX_LENG = 150
USERNAME_LENG = 30

TAG_MAX_LENG = 200

ING_MAX_LENG = 200
ING_MIN_AMOUNT_VALUE = 1
ING_MAX_AMOUNT_VALUE = 32000

RECIPE_MAX_LENG = 200
RECIPE_MIN_COOK_VALUE = 1
RECIPE_MAX_COOK_VALUE = 32000

# api constants

PAGINATION_PAGE_SIZE = 6
