name: Main Foodgram workflow

on:
  push:
    branches:
      - master
jobs:
  backend_test:
    name: Check Python Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9,]
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./backend/requirements.txt
      - name: Test flake8
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
          DB_HOST: localhost
          DB_PORT: 5432 
        run: |
          python -m flake8 backend/
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - backend_test
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login Doker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/final_backend:latest
  build_frontend_and_push_to_docker_hub:
    name: Push frontend Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - 
        name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Push frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/final_frontend:latest
  deploy:
      name: Deploy product
      runs-on: ubuntu-latest
      needs:
        - build_and_push_to_docker_hub
        - build_frontend_and_push_to_docker_hub
      
      steps:
        - 
          name: Check out the repo
          uses: actions/checkout@v2
        -
          name: Copy docker-compose.yml via ssh
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_LOGIN }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
            source: "infra"
            target: 'foodgram'
        -
          name: Executing remote ssh commands to deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_LOGIN }}
            key: ${{ secrets.SSH_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}

            scripts: |
              cd foodgram/infra
              sudo npm cache clean --force
              sudo apt clean
              sudo journalctl --vacuum-time=1d
              sudo docker system prune -af
              sudo docker compose pull
              sudo docker compose down
              sudo docker compose up -d
              sudo docker compose exec backend python manage.py makemigrations
              sudo docker compose exec backend python manage.py migrate
              sudo docker compose exec backend python manage.py collectstatic --no-input
  send_message:
    name: Send a message when deploy is successful
    runs-on: ubuntu-latest
    needs:
      - deploy
      
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Kittygram Деплой успешно выполнен!
            Автор: ${{ github.actor }},
            Сообщение коммита: ${{ github.event.commits[0].message }},
            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }}